# Generated by Django 3.2.12 on 2022-05-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
