apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer1
  name: consumer1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer1
    spec:
      containers:
        - image: salazarslytherin/comorb-ms:1.1
          name: consumer1
          ports:
            - containerPort: 8086
          resources: {}
      restartPolicy: Always
status: {}
