version: '3.8'
services:
  rabbit_mq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
  consumer:
    image: salazarslytherin/vaccine-ms:4.5
    restart: on-failure:10
    depends_on:
      - rabbit_mq
    # volumes:
    #   - ../ms_scowin_vac_drive/:/usr/src/app/
    ports:
      - 8085:8085

  publisher:
    image: salazarslytherin/student-ms:4.5
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8084:8084
    restart: on-failure:10
    depends_on:
      - rabbit_mq
volumes:
    rabbit_mqdata:
      driver: local