apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit-mq
  name: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbit-mq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit-mq
    spec:
      containers:
        - image: rabbitmq:3.8-rc-management
          name: rabbit-mq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/rabbitmq/data
              name: rabbit-mqdata
      restartPolicy: Always
      volumes:
        - name: rabbit-mqdata
          persistentVolumeClaim:
            claimName: rabbit-mqdata
status: {}
