# Generated by Django 3.2.12 on 2022-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVaccination',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('aadharID', models.CharField(max_length=12)),
                ('existingComorbidites', models.CharField(blank=True, max_length=300, null=True)),
                ('vaccineName', models.CharField(max_length=32)),
                ('vaccinationStatus', models.CharField(choices=[('Registered', 'Registered'), ('Not Registered', 'Not Registered'), ('Partially Vaccinated', 'Partially Vaccinated'), ('Fully Vaccinated', 'Fully Vaccinated')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinationDate', models.DateField()),
                ('vaccineName', models.CharField(max_length=32)),
                ('dosesAvailable', models.PositiveIntegerField(default=100)),
                ('slots', models.PositiveIntegerField(default=10)),
                ('driveApproval', models.CharField(choices=[('Created', 'Created'), ('In-Process', 'In-Process'), ('Approval', 'Approval'), ('Rejected', 'Rejected')], max_length=32)),
                ('driveStatus', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=32)),
            ],
        ),
    ]
