# Generated by Django 3.2.12 on 2022-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_drive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinedrive',
            old_name='vaccinationDate',
            new_name='vacdriveDate',
        ),
        migrations.AlterField(
            model_name='studentvaccination',
            name='vaccinationStatus',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='vaccinedrive',
            name='driveApproval',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='vaccinedrive',
            name='driveStatus',
            field=models.CharField(max_length=32),
        ),
    ]
