# Generated by Django 3.2.12 on 2022-05-15 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vac_drive', '0002_auto_20220515_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvaccination',
            name='dosage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentvaccination',
            name='vaccinationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentvaccination',
            name='vaccineName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='VaccineDrive', to='vac_drive.vaccinedrive'),
        ),
    ]
