# Generated by Django 3.2.12 on 2022-05-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_drive', '0005_auto_20220515_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvaccination',
            name='vaccinationDate',
            field=models.DateTimeField(),
        ),
    ]
