# Generated by Django 3.2.12 on 2022-05-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vac_drive', '0007_alter_studentvaccination_vaccinationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvaccination',
            name='student',
        ),
    ]
