# Generated by Django 3.2.12 on 2022-05-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vac_drive', '0010_auto_20220515_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentvaccination',
            old_name='student',
            new_name='studentDtls',
        ),
    ]
