# Generated by Django 3.2.12 on 2022-05-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vac_drive', '0011_rename_student_studentvaccination_studentdtls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentvaccination',
            old_name='studentDtls',
            new_name='student',
        ),
    ]
