# Generated by Django 3.2.12 on 2022-05-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=2)),
                ('section', models.CharField(max_length=1)),
                ('aadharID', models.CharField(max_length=12)),
                ('existingComorbidites', models.CharField(blank=True, max_length=300, null=True)),
                ('bloodGroup', models.CharField(max_length=3)),
            ],
        ),
    ]
